version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: langchef_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: langchef
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.dev
    container_name: langchef_backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "8001:8000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/langchef
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=true
      # AWS Credentials
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_REGION=us-east-1
      # AWS SSO Configuration
      - AWS_SSO_START_URL=${AWS_SSO_START_URL}
      - AWS_SSO_REGION=${AWS_SSO_REGION}
      - AWS_SSO_ACCOUNT_ID=${AWS_SSO_ACCOUNT_ID}
      - AWS_SSO_ROLE_NAME=${AWS_SSO_ROLE_NAME}
    command: python -m backend.main

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.dev
    container_name: langchef_frontend
    volumes:
      # Development hot-reloading for frontend code
      - ./frontend/src:/app/src
    ports:
      - "3001:3000"
    depends_on:
      - backend
      - agent-api
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8001
      - REACT_APP_AGENT_API_URL=http://localhost:5001

  agent-api:
    build:
      context: .
      dockerfile: agent-api/Dockerfile
    container_name: langchef_agent_api
    volumes:
      - ./agent-api:/app
    ports:
      - "5001:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - CORS_ORIGIN=http://localhost:3001

volumes:
  postgres_data: 