#!/usr/bin/env python3
"""Render docs/AGENT-CONTRACT.md from langchef.core.contract.

The prose is here; the tables come from the code, so the document and the
implementation cannot drift. ``--check`` fails if the committed file is stale,
which is how CI keeps them honest.
"""

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from langchef.core.contract import COMMANDS, RULES  # noqa: E402
from langchef.core.exits import REASON, Exit  # noqa: E402

DOC = ROOT / "docs" / "AGENT-CONTRACT.md"

PREAMBLE = """<!-- Generated by scripts/render_contract.py. Do not edit by hand. -->
# The agent contract

**Version 1** · the interface between a model that decides and a binary that
computes. This file is generated from `src/langchef/core/contract.py`; run
`python scripts/render_contract.py` after changing it, and `langchef contract`
to read the same thing as JSON.

## Division of labour

The agent chooses what to look at and says what it means. **The CLI produces
every number.** Model spend goes on judgement and synthesis, never on
arithmetic: a run that costs $0.40 in judge calls should cost nothing in
reasoning tokens to add up.

## Rules
"""

MIDDLE = """
## Commands

`implemented` tracks what exists today; `milestone` is where the rest lands
(see [Build Order](https://claude.ai/code/artifact/b3e1d521-3f23-475d-8a63-b46c507860f1)).
"""

EXITS = """
## Exit codes

The approval gates and the pre-registration rule cannot live in a prompt. A
model asked nicely not to read out early will, eventually, read out early — and
the whole differentiation rests on it not doing that. So the refusals are exit
codes, and an agent cannot argue with a non-zero exit.
"""

PERMISSIONS = """
## What LangChef may read, write, spend and decide

| | |
|---|---|
| **Read** | Whatever the read-only credentials it was given can reach. Never a write credential. |
| **Write** | The eval workspace (`evals/`) and configured notification channels. Nothing else. Anything further goes through a pull request. |
| **Spend** | Up to the per-run cap in `langchef.toml`. On exhaustion it stops, exits `4`, and reports what was left undone. |
| **Decide** | Nothing that ships. It proposes; a human approves at three gates — the rubric, the experiment design including its stopping rule, and the decision itself. |

## Caching and pins

Judge results are content-addressed on **input hash + rubric hash + model pin**.
A rerun is therefore free and byte-identical, and a rubric edit is a diff and a
new hash rather than a silent drift. Every run records the judge model, its
version, and the rubric hash; a mismatch against a baseline exits `5` rather
than comparing across a moved instrument.
"""


def render() -> str:
    lines = [PREAMBLE]
    lines += [f"- {rule}" for rule in RULES]
    lines.append(MIDDLE)
    lines.append("| Command | Does | Determinism | Writes | Milestone | Implemented |")
    lines.append("|---|---|---|---|---|---|")
    for c in COMMANDS:
        mark = "yes" if c.implemented else "—"
        lines.append(
            f"| `langchef {c.name}` | {c.summary} | {c.determinism} | "
            f"`{c.writes}` | {c.milestone} | {mark} |"
        )
    lines.append(EXITS)
    lines.append("| Code | Meaning |")
    lines.append("|---|---|")
    for code in Exit:
        lines.append(f"| `{int(code)}` | {REASON[code]} |")
    lines.append(PERMISSIONS)
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if the committed file is stale")
    args = parser.parse_args()

    rendered = render()
    if args.check:
        current = DOC.read_text(encoding="utf-8") if DOC.is_file() else ""
        if current != rendered:
            print(
                "FAIL: docs/AGENT-CONTRACT.md is stale — run scripts/render_contract.py",
                file=sys.stderr,
            )
            return 1
        print("ok: agent contract is up to date", file=sys.stderr)
        return 0

    DOC.parent.mkdir(parents=True, exist_ok=True)
    DOC.write_text(rendered, encoding="utf-8")
    print(f"wrote {DOC.relative_to(ROOT)}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
