name: Python Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: llm_workflow_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install uv
      run: pip install uv
    
    - name: Install dependencies with uv
      working-directory: ./backend
      run: |
        uv pip install -e .
        uv pip install -e ".[dev]"
    
    - name: Lint with black and isort
      working-directory: ./backend
      run: |
        uv pip run black --check .
        uv pip run isort --check .
    
    - name: Type check with mypy
      working-directory: ./backend
      run: uv pip run mypy .
    
    - name: Test with pytest
      working-directory: ./backend
      env:
        DATABASE_URL: postgresql+asyncpg://postgres:postgres@localhost:5432/llm_workflow_test
        TESTING: true
      run: uv pip run pytest 